"""GeneratorContext (port of ``generator/GeneratorContext.ts``)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

from emf_codegen.generator.import_resolver import ImportResolver
from emf_codegen.generator.type_mapper import TypeMapper

if TYPE_CHECKING:
    from emf_codegen.generator.generator_options import GeneratorOptions
    from emf_codegen.genmodel import GenModel

_DEFAULT_HEADER = (
    "# This file was generated by emfpy-codegen.\n"
    "# DO NOT EDIT - changes will be overwritten.\n"
)


@dataclass
class Diagnostic:
    level: Literal["info", "warning", "error"]
    message: str
    source: str | None = None


class GeneratorContext:
    """State shared across a generation run."""

    def __init__(self, gen_model: GenModel, options: GeneratorOptions) -> None:
        self.gen_model = gen_model
        self.options = options
        self.type_mapper = TypeMapper()
        self.import_resolver = ImportResolver()
        self.diagnostics: list[Diagnostic] = []

    def info(self, message: str, source: str | None = None) -> None:
        self.diagnostics.append(Diagnostic("info", message, source))

    def warn(self, message: str, source: str | None = None) -> None:
        self.diagnostics.append(Diagnostic("warning", message, source))

    def error(self, message: str, source: str | None = None) -> None:
        self.diagnostics.append(Diagnostic("error", message, source))

    def has_errors(self) -> bool:
        return any(d.level == "error" for d in self.diagnostics)

    def get_file_header(self) -> str:
        if self.options.file_header:
            return self.options.file_header
        if self.gen_model.copyright_text:
            body = "\n".join(f"# {line}" for line in self.gen_model.copyright_text.split("\n"))
            return body + "\n"
        return _DEFAULT_HEADER
